src/main/java/ch/ultrasoft/timetracker/model/ExportModel.java
package ch.ultrasoft.timetracker.model;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.inject.Inject;

import ch.ultrasoft.timetracker.beans.UserBean;
import ch.ultrasoft.timetracker.controller.ScheduleController;

public class ExportModel implements Serializable {

	private static final long serialVersionUID = 1L;

	@Inject
	private ScheduleController scheduleController;

	private UserBean userBean;

	private Date date;
	private List<Schedule> schedules = new ArrayList<>();
	private Schedule allInOne = null;
	private String description = null;
	private SimpleDateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy HH:mm");

	public String getDescription() {
		if (description == null) {
			description = "";
			for (int i = schedules.size() - 1; i >= 0; i--) {
				if ((schedules.get(i).getTitle() != null && !schedules.get(i).getTitle().isEmpty())
						|| (schedules.get(i).getDescription() != null && !schedules.get(i).getDescription().isEmpty())) {
					description += dateFormat.format(date) + " " + userBean.getUser().getKuerzel() + ": "
							+ (schedules.get(i).getTitle() != null ? schedules.get(i).getTitle() + "\n" : "")
							+ (schedules.get(i).getDescription() != null ? schedules.get(i).getDescription() + "\n***" : "***");}
			}
		}
		return description;
	}

	public ExportModel(Date date, UserBean userBean) {
		this.date = date;
		this.userBean = userBean;
	}

	public Schedule getAllInOne() {
		if (allInOne == null) {
			int timeUsed = 0;
			for (Schedule s : schedules) {
				allInOne = s;
				timeUsed += s.getTimeUsed();
			}
			allInOne.setTimeUsed(timeUsed);
		}
		return allInOne;
	}

	public double getTimeInHours() {
		return Math.round(((getAllInOne().getTimeUsed() * 4) / 60.) / 60.) / 4.;
	}

	public void setTimeInHours(double timeUsed) {
		getAllInOne().setTimeUsed((int) (timeUsed * 60 * 60));
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public List<Schedule> getSchedules() {
		return schedules;
	}

	public void setSchedules(List<Schedule> schedules) {
		this.schedules = schedules;
	}

}

src/main/java/ch/ultrasoft/timetracker/model/Task.java
package ch.ultrasoft.timetracker.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Lob;

import ch.ultrasoft.timetracker.interfaces.Keyable;

@Entity
public class Task extends AbstractEntity implements Serializable, Keyable {

	private static final long serialVersionUID = -1968506310371095123L;

	@Column
	private String title;

	@Column
	@Lob
	private String description;

	@Column
	private String idExport;

	@Column
	private String status;

	@Column
	private Date dueDate;

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getIdExport() {
		return idExport;
	}

	public void setIdExport(String idExport) {
		this.idExport = idExport;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getDueDate() {
		return dueDate;
	}

	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}

	@Override
	public String toString() {
		return "Task [title=" + title + ", description=" + description + ", idExport=" + idExport + ", getId()="
				+ getId() + ", dueDate=" + dueDate + "]";
	}
}

src/main/java/ch/ultrasoft/timetracker/controller/TaskController.java
package ch.ultrasoft.timetracker.controller;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;

import javax.annotation.PostConstruct;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.EntityTransaction;

import org.apache.log4j.Logger;

import ch.ultrasoft.timetracker.model.ExportModel;
import ch.ultrasoft.timetracker.model.Query;
import ch.ultrasoft.timetracker.model.Schedule;
import ch.ultrasoft.timetracker.model.Task;
import ch.ultrasoft.timetracker.utils.SQLUtil;

@Named("taskController")
@ViewScoped
public class TaskController extends AbstractCrudController<Task> {

    private static final long serialVersionUID = 7128810771691555739L;
    private static final Logger LOGGER = Logger.getLogger(TaskController.class);

    private List<Map<String, List<Object>>> columnsBySQL = new ArrayList<>();
    private List<Object> filteredColumnsBySQL = new ArrayList<>();

    private int seconds;
    private Schedule schedule = new Schedule();

    private Map<String, ExportModel> toExport = new TreeMap<>();

    @Inject
    private ScheduleController scheduleController;

    @Inject
    private QueryController queryController;

    public TaskController() {
        this(Task.class);
    }

    public TaskController(Class<Task> clazz) {
        super(clazz);
    }

    @PostConstruct
    public void init() {
        initRecords();
    }

    public void incrementSecond() {
        seconds++;
    }

    @Override
    public void createRecord() {
        super.createRecord();
        initRelatedSchedules();
    }

    @Override
    public void saveSelected() {
        schedule.setTimeUsed(schedule.getTimeUsed() + seconds);
        schedule.setDate(new Date());
        try {
            schedule.setTask(getSelectedRecord());
            schedule = (Schedule) getService().save(schedule);
            setSelectedRecord(schedule.getTask());
            initRelatedSchedules();
            drawFacesInfoMessage("Record saved", "");
        } catch (Exception e) {
            LOGGER.error("Failed to save record", e);
            drawFacesError("Failed to save record: " + e.getMessage(), "");
        } finally {
            seconds = 0;
            schedule = new Schedule();
            initRecords();
        }
    }

    public void setSelectedRecord(Map<String, Object> map) {
        Task t = new Task();
        t.setIdExport(map.get("idExport").toString());
        setSelectedRecord(t);
        try {
            getSelectedRecord().setTitle(map.get("title").toString());
        } catch (Exception e) {
            LOGGER.error("title not found from IMPORT_TASKS query");
        }
        try {
            getSelectedRecord().setDescription(map.get("description").toString());
        } catch (Exception e) {
            LOGGER.error("description not found from IMPORT_TASKS query");
        }
        try {
            getSelectedRecord().setDueDate(map.get("dueDate").toString().trim().equals("0") ? null : new Date(Math.round(Double.valueOf(map.get("dueDate").toString()))));
        } catch (Exception e) {
            LOGGER.error("dueDate (long) not found from IMPORT_TASKS query");
        }
        try {
            getSelectedRecord().setStatus(map.get("status").toString());
        } catch (Exception e) {
            LOGGER.error("status not found from IMPORT_TASKS query");
        }
    }

    @Override
    public void setSelectedRecord(Task selectedRecord) {
        seconds = 0;
        if (selectedRecord != null && selectedRecord.getId() == null && selectedRecord.getIdExport() != null)
            for (Task t : getRecords()) {
                if (t != null && t.getIdExport() != null && t.getIdExport().equals(selectedRecord.getIdExport())) {
                    selectedRecord = t;
                    break;
                }
            }
        super.setSelectedRecord(selectedRecord);
        initRelatedSchedules();
        LOGGER.debug("setSelectedRecord: " + selectedRecord);
    }

    private void initRelatedSchedules() {
        if (scheduleController != null)
            scheduleController.initRelatedSchedules(getSelectedRecord());
    }

    @Override
    public void deleteSelected() {
        initRelatedSchedules();
        try {
            for (Schedule s : scheduleController.getRelatedSchedules())
                getService().delete(s);
        } catch (Exception e) {
            e.printStackTrace();
        }
        super.deleteSelected();
    }

    public void deleteExported() {
        final List<Long> notToDelete = getService().getEm().createQuery("SELECT DISTINCT s.task.id FROM Schedule s WHERE s.exported = false", Long.class).getResultList();
        try {
            getService().getEm().getTransaction().begin();
            getService().getEm().createQuery("DELETE FROM Schedule s WHERE s.task.id NOT IN (:notToDelete)")
                    .setParameter("notToDelete", notToDelete)
                    .executeUpdate();
            getService().getEm().createQuery("DELETE FROM Task t WHERE t.id NOT IN (:notToDelete)")
                    .setParameter("notToDelete", notToDelete)
                    .executeUpdate();
            getService().getEm().flush();
            getService().getEm().getTransaction().commit();
            drawFacesInfoMessage("Exported record(s) deleted", "");
            initRecords();
        } catch (Exception e) {
            if (getService().getEm().getTransaction().isActive())
                getService().getEm().getTransaction().rollback();
            LOGGER.error("Deleting exported Tasks failed", e);
            drawFacesError("ERROR Deleting exported tasks: " + e.getMessage(), "");
        }
    }

    public void initColumnsBySQL() {
        try {
            SQLUtil sqlService = SQLUtil.createInstance();
            columnsBySQL = new ArrayList<>();
            for (String query : queryController.getSelectTasksQuery().getQuery().split(";")) {
                columnsBySQL.add(sqlService.sqlToTasks(query.replaceAll(":user.username", userBean.getUser().getUsername())));
            }
        } catch (Exception e) {
            LOGGER.error("initColumnsBySQL failed", e);
            drawFacesError("ERROR Importing Tasks: " + e.getMessage(), "");
        }
    }


    public void prepareExport(Map<String, Object> map) {
        setSelectedRecord(map);
        prepareExport(getSelectedRecord());
    }

    public void prepareExport(Task t) {
        if (t != null) {
            setSelectedRecord(t);
            toExport = new TreeMap<>();
            initRelatedSchedules();
            for (Schedule s : scheduleController.getRelatedSchedules()) {
                String date = new SimpleDateFormat("yyyy-MM-dd").format(s.getDate());
                if (!s.isExported()) {
                    if (!toExport.containsKey(date))
                        toExport.put(date, new ExportModel(s.getDate(), userBean));
                    toExport.get(date).getSchedules().add(s);
                }
            }
        }
    }

    private String buildExportQuery(String query, Map.Entry<String, ExportModel> e, int exportedIdSchedule) {
        return query
                .replaceAll(":insered.schedule.id", (exportedIdSchedule + "").replaceAll("'", "''"))
                .replaceAll(":schedule.timeUsed", "" + e.getValue().getAllInOne().getTimeUsed())
                .replaceAll(":task.idExport", e.getValue().getAllInOne().getTask().getIdExport().replaceAll("'", "''"))
                .replaceAll(":task.dueDate", new SimpleDateFormat("yyyy-MM-dd").format(e.getValue().getAllInOne().getTask().getDueDate() != null ? e.getValue().getAllInOne().getTask().getDueDate() : new Date()).replaceAll("'", "''"))
                .replaceAll(":schedule.description.summary", e.getValue().getDescription().replaceAll("'", "''"))
                .replaceAll(":task.title", e.getValue().getAllInOne().getTask().getTitle().replaceAll("'", "''"))
                .replaceAll(":user.username", userBean.getUser().getUsername().replaceAll("'", "''"))
                .replaceAll(":user.sprint", (userBean.getUser().getAktuellerSprint() != null ? userBean.getUser().getAktuellerSprint() : "no spring selected").replaceAll("'", "''"))
                .replaceAll(":schedule.inHoursTimeUsed", (e.getValue().getTimeInHours() + "").replaceAll("'", "''"))
                .replaceAll(":schedule.dateAsLong", (e.getValue().getAllInOne().getDate().getTime() + "").replaceAll("'", "''"))
                .replaceAll(":schedule.dateAsISO", new SimpleDateFormat("yyyy-MM-dd").format(e.getValue().getAllInOne().getDate()).replaceAll("'", "''"));
    }

    public void exportSchedules() {
        List<Schedule> exported = new ArrayList<>();
        Query q = queryController.getInsertTaskQuery();
        try {
            SQLUtil sqlService = SQLUtil.createInstance();
            for (Map.Entry<String, ExportModel> e : toExport.entrySet()) {


                // WRITE HISTORY
                Query qHistory = queryController.getHistoryTaskQuery();

                if (qHistory != null) {
                    String queryHistory = buildExportQuery(qHistory.getQuery(), e, 0);
                    sqlService.executeUpdate(queryHistory);
                }

                int inseredId = 0;
                String query = null;
                if (e.getValue().getTimeInHours() != 0.0) {
                    query = buildExportQuery(q.getQuery(), e, 0);
                    inseredId = sqlService.executeUpdate(query);
                }

                EntityTransaction tx = null;
                try {
                    for (String sql : queryController.getInsertTaskScheduleRelationQuery().getQuery().split(";")) {
                        if (e.getValue().getTimeInHours() == 0.0 && sql.contains(":insered.schedule.id")) {
                            continue;

src/main/webapp/pages/fragments/task/editTask.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:pm="http://primefaces.org/mobile"
                xmlns:pe="http://primefaces.org/ui/extensions"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui">


    <p:dialog
            closable="true"
            id="templateCopyPaste"
            widgetVar="templateCopyPaste">

        <ui:include src="/pages/fragments/templates/templatesCopyPaste.xhtml"/>

    </p:dialog>

    <h:form id="editPageForm">

        <p:messages id="msgs" autoUpdate="false"/>
        <p:panelGrid columns="4" style="text-align:center;">
            <p:commandButton icon="fa fa-save ui-icon-check" value="" validateClient="true"
                             update="editPageForm msgs" styleClass="ui-btn-inline"
                             actionListener="#{taskController.saveSelected()}"
                             title="#{i18n['label.speichern']}"/>

            <p:commandButton icon="fa fa-upload ui-icon-cloud" styleClass="ui-btn-inline"
                             value=""
                             onclick="PF('timer').pause()"
                             disabled="#{not taskController.hasTaskUnexportedSchedules(taskController.selectedRecord.idExport)}"
                             actionListener="#{taskController.prepareExport(taskController.selectedRecord)}"
                             update=":editPage:exportDialog" title="#{i18n['label.export']}"
                             oncomplete="PF('exportDialog').show();"/>

            <p:commandButton icon="fa fa-cut ui-icon-check" value="" immediate="true"
                             styleClass="ui-btn-inline"
                             oncomplete="PF('templateCopyPaste').show()"
                             title="#{i18n['label.templates']}"/>

            <p:commandButton id="back" update=":first:dataTable:inportedTasksForm :first:dataTable:tasksForm"
                             styleClass="ui-btn-inline" title="#{i18n['label.abbrechen']}"
                             validateClient="false" style="margin-left:10px;"
                             oncomplete="$('#editPage\\:editPageForm\\:showFirstButton').click()"
                             value="" icon="fa fa-remove ui-icon-delete"/>
        </p:panelGrid>


        <p:button id="showFirstButton" outcome="pm:first"
                  title="#{i18n['label.abbrechen']}" style="display: none;" value=""
                  icon="fa fa-remove ui-icon-delete"/>

        <p:panel
                header="#{i18n['label.task']} : #{taskController.selectedRecord.status}"
                toggleable="true" collapsed="false">

            <pm:field>
                <p:outputLabel for="idExport" value="#{i18n['label.task.exportid']}"/>

                <p:inputText
                        rendered="#{empty taskController.selectedRecord.idExport}"
                        id="idExport"
                        value="#{taskController.selectedRecord.idExport}" />

                <p:commandLink
                        rendered="#{not empty taskController.selectedRecord.idExport}"
                        value="# #{taskController.selectedRecord.idExport}"
                        onclick="window.open ('http://192.168.48.212/egroupware/index.php?menuaction=infolog.infolog_ui.edit&amp;info_id=#{taskController.selectedRecord.idExport}', 'Google', config='height=600,width=800,border=0;');"/>
            </pm:field>

            <pm:field>
                <p:outputLabel for="dueDateInput"
                               value="#{i18n['label.duedate']}"/>

                <p:inputText style="width: 195px;" id="dueDateInput"
                             type="date" pattern="dd.MM.yyyy"
                             value="#{taskController.selectedRecord.dueDate}">
                    <f:convertDateTime pattern="yyyy-MM-dd"/>
                    <p:ajax
                            listener="#{taskController.updateDueDate()}"
                            update="editPageForm msgs" title="#{i18n['label.update.duedate']}"/>
                </p:inputText>
            </pm:field>


            <pm:field>
                <p:outputLabel for="taskTitle" value="#{i18n['label.task.title']}"/>
                <p:inputText required="true" id="taskTitle"
                             readonly="#{not empty taskController.selectedRecord.idExport}"
                             value="#{taskController.selectedRecord.title}"/>
            </pm:field>

            <pm:field>
                <p:outputLabel for="taskDescription"
                               value="#{i18n['label.task.description']}"/>
                <p:inputTextarea id="taskDescription"
                                 readonly="#{not empty taskController.selectedRecord.idExport}"
                                 value="#{taskController.selectedRecord.description}"/>
            </pm:field>
        </p:panel>
        <p:panel header="#{i18n['label.schedules']}" toggleable="true"
                 collapsed="false">
            <p:tabView id="tabViewSchedules">
                <p:tab title="#{i18n['label.current.schedule']}">
                    <p:remoteCommand name="incrementSecond" async="true"
                                     action="#{taskController.incrementSecond()}"
                                     partialSubmit="true" process="@this"/>

                    <center>
                        <h1 class="first">
                            <pe:timer widgetVar="timer" ontimerstep="incrementSecond()"
                                      timeout="2000000000" format="HH:mm:ss" forward="true"
                                      singleRun="false" autoStart="true"/>
                        </h1>
                    </center>
                    <p:panelGrid columns="2">
                        <p:commandButton icon="fa fa-play ui-icon-clock" value=""
                                         title="#{i18n['label.start']}" onclick="PF('timer').start()"
                                         style="margin-right:10px;"/>
                        <p:commandButton icon="fa fa-pause ui-icon-clock" value=""
                                         title="#{i18n['label.start']}" onclick="PF('timer').pause()"
                                         style="margin-left:10px;"/>
                    </p:panelGrid>
                    <pm:field>
                        <p:outputLabel for="scheduleTitle"
                                       value="#{i18n['label.schedule.title']}"/>
                        <p:inputText id="scheduleTitle"
                                     value="#{taskController.schedule.title}"/>
                    </pm:field>
                    <pm:field>
                        <p:outputLabel for="scheduleDescription"
                                       value="#{i18n['label.schedule.description']}"/>
                        <p:inputTextarea id="scheduleDescription"
                                         value="#{taskController.schedule.description}"/>
                    </pm:field>
                </p:tab>
                <p:tab title="#{i18n['label.related.schedules.grouped']}">
                    <p:dataTable
                            value="#{scheduleController.dayTimeTrackerMap.entrySet().toArray()}"
                            var="r">
                        <p:column headerText="#{i18n['label.datum']}">
                            <h:outputText value="#{r.key}"/>
                        </p:column>
                        <p:column headerText="#{i18n['label.stunden']}">
                            <h:outputText value="#{((r.value / 60) / 60)}"/>
                        </p:column>
                    </p:dataTable>
                </p:tab>
                <p:tab title="#{i18n['label.all.related.schedules']}">
                    <p:dataTable value="#{scheduleController.relatedSchedules}"
                                 var="r">
                        <p:column headerText="#{i18n['label.title']}">
                            <p:inputText value="#{r.title}" title="creator: #{r.creator}"/>
                        </p:column>
                        <p:column headerText="#{i18n['label.schedule.description']}">
                            <p:inputTextarea value="#{r.description}" title="creator: #{r.creator}"/>
                        </p:column>
                        <p:column headerText="#{i18n['label.sekunden']}"
                                  style="width:80px;">
                            <p:inputNumber value="#{r.timeUsed}"/>
                            <!-- </p:column>
                        <p:column headerText="#{i18n['label.exportiert']}" style="width:80px;"> -->
                            <p:selectBooleanCheckbox title="#{i18n['label.exportiert']}"
                                                     disabled="#{r.creator ne userBean.user.username}"
                                                     itemLabel="#{i18n['label.exportiert']}" value="#{r.exported}"/>
                        </p:column>
                        <p:column style="width:60px;">
                            <p:commandButton icon="fa fa-save ui-icon-check" value=""
                                             title="#{i18n['label.speichern']}" styleClass="ui-btn-inline"
                                             actionListener="#{scheduleController.save(r)}"
                                             disabled="#{r.creator ne userBean.user.username}"
                                             update=":editPage:editPageForm:msgs"/>
                        </p:column>
                        <p:column style="width:60px;">
                            <p:commandButton icon="fa fa-trash ui-icon-delete" value=""
                                             title="#{i18n['label.loeschen']}"
                                             oncomplete="PF('deleteScheduleDialog').show()"
                                             styleClass="ui-btn-inline"
                                             disabled="#{r.creator ne userBean.user.username}"
                                             actionListener="#{scheduleController.setSelectedRecord(r)}"
                                             update=":editPage:deleteScheduleDialog"/>
                        </p:column>
                    </p:dataTable>
                </p:tab>
            </p:tabView>
        </p:panel>
    </h:form>

    <p:dialog id="deleteScheduleDialog" widgetVar="deleteScheduleDialog">
        <h:form>
            <center>
                <h:outputText value="#{i18n['text.confirm.delete']}"/>
            </center>
            <p:panelGrid columns="2" style="text-align:center;">
                <p:commandButton value="" icon="fa fa-check ui-icon-check"
                                 styleClass="ui-btn-inline" title="#{i18n['label.loeschen']}"
                                 actionListener="#{scheduleController.deleteSelected()}"
                                 update=":editPage:editPageForm :editPage:editPageForm:msgs"
                                 oncomplete="PF('deleteScheduleDialog').hide();"/>

                <p:commandButton value="" icon="fa fa-remove ui-icon-delete"
                                 styleClass="ui-btn-inline" style="margin-left:10px;"
                                 title="#{i18n['label.abbrechen']}"
                                 oncomplete="PF('deleteScheduleDialog').hide();"/>
            </p:panelGrid>
        </h:form>
    </p:dialog>

    <p:dialog id="exportDialog" widgetVar="exportDialog"
              style="heigth:500px;" closable="false">
        <h:form id="exportForm">

            <p:dataList var="r"
                        emptyMessage="#{i18n['label.export.keine.schedules.gefunden']}"
                        value="#{taskController.toExport.entrySet().toArray()}">
                <p:column>
                    <h:outputText value="#{r.key}"/>
                    <!-- <p:dataList var="d" value="#{r.value}"> -->
                    <p:inputText value="#{r.value.timeInHours}"/>
                    <!-- </p:dataList> -->
                </p:column>
            </p:dataList>

            <p:panelGrid columns="2" style="text-align:center;">
                <p:commandButton value="" icon="fa fa-check ui-icon-check"
                                 title="#{i18n['label.exportieren']}"
                                 actionListener="#{taskController.exportSchedules()}"
                                 update=":editPage:editPageForm :editPage:editPageForm:msgs"
                                 styleClass="ui-btn-inline"
                                 oncomplete="PF('exportDialog').hide();PF('timer').start();"
                                 disabled="#{empty taskController.toExport}"/>

                <p:commandButton value="" icon="fa fa-remove ui-icon-delete"
                                 title="#{i18n['label.abbrechen']}"
                                 update=":editPage:editPageForm" style="margin-left:10px;"
                                 oncomplete="PF('exportDialog').hide();PF('timer').start();"
                                 styleClass="ui-btn-inline"/>
            </p:panelGrid>
        </h:form>
    </p:dialog>
</ui:composition>